### PR TITLE
Changed build set versions and values sha256

### PR DESCRIPTION
**Pull request by esloch**
--Changed set version for 3.2.2.
--Changed build number to 0.
--Changed value md5.
--Changed file extension zip to tar.gz.

ps: cc @xmnlab

### CODE REVIEW

**Comment by astrojuanlu** [comment]
@conda-forge-admin please rerender

**Comment by xmnlab** [comment]
@esloch 

it seems you have used sha256. 

just change to the correct md5:

```
md5: c8099b3b6c6bdd1aebc1e3a19809cee4
```

**Comment by xmnlab** [comment]
@conda-forge-admin please rerender

**Comment by xmnlab** [comment]
@esloch sorry I forgot to say you should rebase your code first.

that is because @Juanlu001 ran here the command to rerender ... and it add more changes in your code ...

so before any change you should run `git pull --rebase`

but I have triggered again the rerender here.  if you go to `files changed` you can see now 25 files were changed! :)

now we just need to wait :)

**Comment by xmnlab** [comment]
it seems it worked! @Juanlu001 could this be merged? thanks @esloch !

**Comment by astrojuanlu** [comment]
Done!

**Pull request merged**
